### ISSUE TITLE
Support for Static Framework

### ISSUE THREAD

**Issue by vijaytholpadi** [sendbird/sendbird-chat-sdk-ios#13]
Hi Sendbird Team,

Wanted to check if it is possible to add Static framework support for Sendbird SDK.

I see that it has been requested in past [here](https://community.sendbird.com/t/does-sendbirdcalls-support-static-framework/3354).

**Comment by vijaytholpadi** [comment]
Hi Team, Any update on this?

**Comment by sf-jed-kyung** [comment]
Hi @vijaytholpadi ,

We currently do not plan to provide a static framework for our SDK. Please elaborate on why you requested such a framework.

**Comment by vijaytholpadi** [comment]
@sf-jed-kyung In our application at Carousell. The both SendBird and SyncManager framework is only used in the main application.

Importing this as a dynamic library increases our application launch times as dyld needs to load it at app launch.

Given that it is only used in main application, a static library is a better fit for our usecase so that there is no impact due to dyld losing overhead. 

It has also been raised by other developers in the first link I have shared in this issue.

**Comment by famous90** [comment]
@vijaytholpadi Hi, I'm an engineering manager for iOS SDK. Thank you for your suggestion. It would be very helpful for us to provide more useful framework. 
As Jed mentioned, we don't have a plan to provide what you suggested in v3 product, and we could consider your suggestion in v4. And I would appreciate it if you share/suggest through official support channel, Sendbird community or Sendbird solution engineers.
